import { SlashCommandBuilder, PermissionFlagsBits, ChannelType } from 'discord.js';
import { ADMIN } from '../utils/permissions.js';

export const command=new SlashCommandBuilder().setName('automod').setDescription('Configura AutoMod.')
    .setDefaultMemberPermissions(ADMIN)
    .addSubcommand(s=>s.setName('setup').setDescription('Muestra reglas AutoMod.'))
    .addSubcommand(s=>s.setName('spam').setDescription('Configura anti-spam.')
      .addBooleanOption(o=>o.setName('enabled').setDescription('Activa o desactiva esta regla.').setRequired(true))
      .addIntegerOption(o=>o.setName('limit').setDescription('Cantidad de mensajes dentro del intervalo.').setMinValue(2).setMaxValue(20).setRequired(true))
      .addStringOption(o=>o.setName('action').setDescription('Acción que se aplicará al detectar la regla.').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}))
      .addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout/ban, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma')))
    .addSubcommand(s=>s.setName('links').setDescription('Configura bloqueo de enlaces.')
      .addBooleanOption(o=>o.setName('enabled').setDescription('Activa o desactiva esta regla.').setRequired(true))
      .addStringOption(o=>o.setName('whitelist').setDescription('Dominios separados por coma'))
      .addStringOption(o=>o.setName('action').setDescription('Acción que se aplicará al detectar la regla.').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}))
      .addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout/ban, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma')))
    .addSubcommand(s=>s.setName('invites').setDescription('Configura bloqueo de invitaciones.')
      .addBooleanOption(o=>o.setName('enabled').setDescription('Activa o desactiva esta regla.').setRequired(true))
      .addStringOption(o=>o.setName('action').setDescription('Acción que se aplicará al detectar la regla.').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}))
      .addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout/ban, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma')))
    .addSubcommand(s=>s.setName('words').setDescription('Configura palabras prohibidas.')
      .addBooleanOption(o=>o.setName('enabled').setDescription('Activa o desactiva esta regla.').setRequired(true))
      .addStringOption(o=>o.setName('words').setDescription('Palabras separadas por coma').setRequired(true))
      .addStringOption(o=>o.setName('action').setDescription('Acción que se aplicará al detectar la regla.').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}))
      .addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout/ban, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma')))
    .addSubcommand(s=>s.setName('mentions').setDescription('Configura límite de menciones.')
      .addBooleanOption(o=>o.setName('enabled').setDescription('Activa o desactiva esta regla.').setRequired(true))
      .addIntegerOption(o=>o.setName('limit').setDescription('Cantidad máxima de menciones permitidas.').setMinValue(1).setMaxValue(20).setRequired(true))
      .addStringOption(o=>o.setName('action').setDescription('Acción que se aplicará al detectar la regla.').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}))
      .addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout/ban, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma')))
    .addSubcommand(s=>s.setName('caps').setDescription('Configura límite de mayúsculas.')
      .addBooleanOption(o=>o.setName('enabled').setDescription('Activa o desactiva esta regla.').setRequired(true))
      .addIntegerOption(o=>o.setName('percentage').setDescription('Porcentaje mínimo de mayúsculas.').setMinValue(50).setMaxValue(100).setRequired(true))
      .addStringOption(o=>o.setName('action').setDescription('Acción que se aplicará al detectar la regla.').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}))
      .addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout/ban, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma')));
