import { SlashCommandBuilder, PermissionFlagsBits, ChannelType } from 'discord.js';
import { ADMIN } from './utils/permissions.js';

export const commands=[
  new SlashCommandBuilder()
     .setName('tickets').setDescription('Sistema de tickets.')
    .addSubcommand(s=>s.setName('panel').setDescription('Crea un panel.')
      .addStringOption(o=>o.setName('nombre').setDescription('Nombre').setRequired(true))
      .addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true))
      .addStringOption(o=>o.setName('titulo').setDescription('Título'))
      .addStringOption(o=>o.setName('descripcion').setDescription('Descripción'))
      .addStringOption(o=>o.setName('color').setDescription('Color HEX'))
      .addStringOption(o=>o.setName('imagen').setDescription('URL imagen'))
      .addStringOption(o=>o.setName('thumbnail').setDescription('URL thumbnail'))
      .addStringOption(o=>o.setName('footer').setDescription('Footer')))
    .addSubcommand(s=>s.setName('categoria').setDescription('Añade categoría.')
      .addStringOption(o=>o.setName('panel').setDescription('Nombre del panel').setRequired(true))
      .addStringOption(o=>o.setName('nombre').setDescription('Nombre').setRequired(true))
      .addStringOption(o=>o.setName('staff').setDescription('Nombres de roles separados por comas').setRequired(true))
      .addStringOption(o=>o.setName('emoji').setDescription('Emoji'))
      .addStringOption(o=>o.setName('descripcion').setDescription('Descripción'))
      .addChannelOption(o=>o.setName('categoria-canal').setDescription('Categoría Discord').addChannelTypes(ChannelType.GuildCategory)))
    .addSubcommand(s=>s.setName('pregunta').setDescription('Añade pregunta.')
      .addStringOption(o=>o.setName('categoria').setDescription('Nombre de la categoría').setRequired(true))
      .addStringOption(o=>o.setName('label').setDescription('Pregunta').setRequired(true))
      .addStringOption(o=>o.setName('placeholder').setDescription('Placeholder'))
      .addBooleanOption(o=>o.setName('obligatoria').setDescription('Obligatoria')))
    .addSubcommand(s=>s.setName('publicar').setDescription('Publica panel.')
      .addStringOption(o=>o.setName('panel').setDescription('Nombre del panel').setRequired(true)))
    .addSubcommand(s=>s.setName('log').setDescription('Configura logs.')
      .addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true)))
    .addSubcommand(s=>s.setName('log-reset').setDescription('Elimina la configuración de logs.'))
    .addSubcommand(s=>s.setName('panel-list').setDescription('Lista paneles.'))
    .addSubcommand(s=>s.setName('panel-renombrar').setDescription('Renombra un panel.')
      .addStringOption(o=>o.setName('nombre').setDescription('Nombre actual del panel').setRequired(true))
      .addStringOption(o=>o.setName('nuevo-nombre').setDescription('Nuevo nombre del panel').setRequired(true)))
    .addSubcommand(s=>s.setName('panel-eliminar').setDescription('Elimina un panel y su configuración.')
      .addStringOption(o=>o.setName('nombre').setDescription('Nombre del panel').setRequired(true))
      .addBooleanOption(o=>o.setName('confirmar').setDescription('Confirma la eliminación').setRequired(true)))
    .addSubcommand(s=>s.setName('panel-reset').setDescription('Elimina TODOS los paneles y su configuración.')
      .addBooleanOption(o=>o.setName('confirmar').setDescription('Confirma el reinicio total').setRequired(true)))
    .addSubcommand(s=>s.setName('categoria-list').setDescription('Lista categorías de un panel.')
      .addStringOption(o=>o.setName('panel').setDescription('Nombre del panel').setRequired(true)))
    .addSubcommand(s=>s.setName('categoria-eliminar').setDescription('Elimina una categoría y su configuración.')
      .addStringOption(o=>o.setName('nombre').setDescription('Nombre de la categoría').setRequired(true))
      .addBooleanOption(o=>o.setName('confirmar').setDescription('Confirma la eliminación').setRequired(true)))
    .addSubcommand(s=>s.setName('pregunta-list').setDescription('Lista preguntas de una categoría.')
      .addStringOption(o=>o.setName('categoria').setDescription('Nombre de la categoría').setRequired(true)))
    .addSubcommand(s=>s.setName('pregunta-eliminar').setDescription('Elimina una pregunta.')
      .addStringOption(o=>o.setName('categoria').setDescription('Nombre de la categoría').setRequired(true))
      .addStringOption(o=>o.setName('label').setDescription('Texto de la pregunta').setRequired(true))
      .addBooleanOption(o=>o.setName('confirmar').setDescription('Confirma la eliminación').setRequired(true)))
    .addSubcommand(s=>s.setName('reclamar').setDescription('Reclama un ticket.')
      .addStringOption(o=>o.setName('ticket').setDescription('ID, canal o número').setRequired(true)))
    .addSubcommand(s=>s.setName('liberar').setDescription('Libera un ticket reclamado.')
      .addStringOption(o=>o.setName('ticket').setDescription('ID, canal o número').setRequired(true)))
    .addSubcommand(s=>s.setName('adduser').setDescription('Añade un usuario al ticket.')
      .addStringOption(o=>o.setName('ticket').setDescription('ID, canal o número').setRequired(true))
      .addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)))
    .addSubcommand(s=>s.setName('removeuser').setDescription('Quita un usuario del ticket.')
      .addStringOption(o=>o.setName('ticket').setDescription('ID, canal o número').setRequired(true))
      .addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)))
    .addSubcommand(s=>s.setName('cerrar').setDescription('Cierra un ticket.')
      .addStringOption(o=>o.setName('ticket').setDescription('ID, canal o número').setRequired(true))
      .addBooleanOption(o=>o.setName('confirmar').setDescription('Confirma el cierre').setRequired(true))
      .addStringOption(o=>o.setName('razon').setDescription('Razón')))
    .addSubcommand(s=>s.setName('reabrir').setDescription('Reabre un ticket cerrado.')
      .addStringOption(o=>o.setName('ticket').setDescription('ID, canal o número').setRequired(true)))
    .addSubcommand(s=>s.setName('renombrar').setDescription('Renombra el canal del ticket.')
      .addStringOption(o=>o.setName('ticket').setDescription('ID, canal o número').setRequired(true))
      .addStringOption(o=>o.setName('nombre').setDescription('Nuevo nombre').setRequired(true)))
    .addSubcommand(s=>s.setName('mover').setDescription('Mueve el ticket de categoría.')
      .addStringOption(o=>o.setName('ticket').setDescription('ID, canal o número').setRequired(true))
      .addChannelOption(o=>o.setName('categoria').setDescription('Categoría Discord').addChannelTypes(ChannelType.GuildCategory).setRequired(true)))
    .addSubcommand(s=>s.setName('prioridad').setDescription('Cambia la prioridad del ticket.')
      .addStringOption(o=>o.setName('ticket').setDescription('ID, canal o número').setRequired(true))
      .addStringOption(o=>o.setName('nivel').setDescription('Prioridad').setRequired(true)
        .addChoices({name:'Baja',value:'low'},{name:'Normal',value:'normal'},{name:'Alta',value:'high'})))
    .addSubcommand(s=>s.setName('stats').setDescription('Estadísticas de tickets.'))
    .addSubcommand(s=>s.setName('transcript').setDescription('Obtiene la transcripción de un ticket.')
      .addStringOption(o=>o.setName('ticket').setDescription('ID, canal o número').setRequired(true))),

  new SlashCommandBuilder()
    .setName('welcome').setDescription('Configura bienvenida.')
    .setDefaultMemberPermissions(ADMIN)
    .addSubcommand(s=>s.setName('set').setDescription('Configura.')
      .addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true))
      .addStringOption(o=>o.setName('mensaje').setDescription('Mensaje').setRequired(true))
      .addStringOption(o=>o.setName('titulo').setDescription('Título'))
      .addStringOption(o=>o.setName('descripcion').setDescription('Descripción'))
      .addStringOption(o=>o.setName('color').setDescription('Color HEX'))
      .addStringOption(o=>o.setName('imagen').setDescription('URL imagen'))
      .addStringOption(o=>o.setName('thumbnail').setDescription('URL thumbnail'))
      .addStringOption(o=>o.setName('footer').setDescription('Footer'))
      .addChannelOption(o=>o.setName('canal-despedida').setDescription('Canal de despedidas').addChannelTypes(ChannelType.GuildText))
      .addStringOption(o=>o.setName('despedida').setDescription('Mensaje de despedida')))
    .addSubcommand(s=>s.setName('reset').setDescription('Elimina la configuración de bienvenida.'))
    .addSubcommand(s=>s.setName('test').setDescription('Prueba la bienvenida.'))
    .addSubcommand(s=>s.setName('preview').setDescription('Previsualiza la bienvenida.')),

  new SlashCommandBuilder()
    .setName('vouch-config').setDescription('Configura vouches.')
    .setDefaultMemberPermissions(ADMIN)
    .addSubcommand(s=>s.setName('set').setDescription('Activa.')
      .addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true))
      .addStringOption(o=>o.setName('roles').setDescription('Nombres de roles separados por comas'))
      .addIntegerOption(o=>o.setName('cooldown').setDescription('Segundos').setMinValue(0))
      .addStringOption(o=>o.setName('titulo').setDescription('Título'))
      .addStringOption(o=>o.setName('descripcion').setDescription('Descripción'))
      .addStringOption(o=>o.setName('color').setDescription('Color HEX'))
      .addStringOption(o=>o.setName('imagen').setDescription('URL imagen'))
      .addStringOption(o=>o.setName('thumbnail').setDescription('URL thumbnail'))
      .addStringOption(o=>o.setName('footer').setDescription('Footer')))
    .addSubcommand(s=>s.setName('reset').setDescription('Desactiva.')),

  new SlashCommandBuilder()
    .setName('vouch').setDescription('Deja una reseña.')
    .addUserOption(o=>o.setName('member').setDescription('Miembro').setRequired(true))
    .addStringOption(o=>o.setName('tipo').setDescription('Tipo').setRequired(true)
      .addChoices({name:'Legit',value:'Legit'},{name:'No Legit',value:'No Legit'}))
    .addIntegerOption(o=>o.setName('rating').setDescription('1-5').setRequired(true).setMinValue(1).setMaxValue(5)),

  new SlashCommandBuilder()
    .setName('autoresponder').setDescription('Gestiona respuestas.')
    .setDefaultMemberPermissions(ADMIN)
    .addSubcommand(s=>s.setName('add').setDescription('Añade.')
      .addStringOption(o=>o.setName('trigger').setDescription('Trigger').setRequired(true))
      .addStringOption(o=>o.setName('respuesta').setDescription('Respuesta').setRequired(true))
      .addStringOption(o=>o.setName('modo').setDescription('Modo')
        .addChoices({name:'Contiene',value:'contains'},{name:'Exacta',value:'exact'}))
      .addStringOption(o=>o.setName('titulo').setDescription('Título embed'))
      .addStringOption(o=>o.setName('descripcion').setDescription('Descripción embed'))
      .addStringOption(o=>o.setName('color').setDescription('Color HEX')))
    .addSubcommand(s=>s.setName('remove').setDescription('Elimina.')
      .addStringOption(o=>o.setName('trigger').setDescription('Trigger').setRequired(true)))
    .addSubcommand(s=>s.setName('list').setDescription('Lista.')),

  new SlashCommandBuilder()
    .setName('presence').setDescription('Rich Presence del bot.')
    .setDefaultMemberPermissions(ADMIN)
    .addSubcommand(s=>s.setName('set').setDescription('Configura.')
      .addStringOption(o=>o.setName('tipo').setDescription('Tipo').setRequired(true)
        .addChoices({name:'Playing',value:'Playing'},{name:'Watching',value:'Watching'},{name:'Listening',value:'Listening'}))
      .addStringOption(o=>o.setName('texto').setDescription('Texto').setRequired(true)))
    .addSubcommand(s=>s.setName('reset').setDescription('Restablece.')),

  new SlashCommandBuilder()
    .setName('purge').setDescription('Elimina mensajes del canal actual.')
    .setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages)
    .addIntegerOption(o=>o.setName('cantidad').setDescription('Cantidad de mensajes a eliminar').setMinValue(1).setMaxValue(10000))
    .addBooleanOption(o=>o.setName('canal').setDescription('Elimina todo el historial del canal actual')),
  new SlashCommandBuilder().setName('help').setDescription('Muestra la ayuda completa de Codek Hub.'),
  new SlashCommandBuilder().setName('variables').setDescription('Muestra variables.'),
  new SlashCommandBuilder().setName('warn').setDescription('Advierte a un usuario.')
    .setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers)
    .addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true))
    .addStringOption(o=>o.setName('razon').setDescription('Razón')),
  new SlashCommandBuilder().setName('mute').setDescription('Aplica timeout a un usuario.')
    .setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers)
    .addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true))
    .addStringOption(o=>o.setName('duracion').setDescription('Ejemplo: 1h, 30m, 1d').setRequired(true))
    .addStringOption(o=>o.setName('razon').setDescription('Razón')),
  new SlashCommandBuilder().setName('unmute').setDescription('Quita el timeout.')
    .setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers)
    .addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)),
  new SlashCommandBuilder().setName('kick').setDescription('Expulsa a un usuario.')
    .setDefaultMemberPermissions(PermissionFlagsBits.KickMembers)
    .addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true))
    .addStringOption(o=>o.setName('razon').setDescription('Razón')),
  new SlashCommandBuilder().setName('ban').setDescription('Banea a un usuario.')
    .setDefaultMemberPermissions(PermissionFlagsBits.BanMembers)
    .addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true))
    .addStringOption(o=>o.setName('razon').setDescription('Razón')),
  new SlashCommandBuilder().setName('unban').setDescription('Desbanea por ID.')
    .setDefaultMemberPermissions(PermissionFlagsBits.BanMembers)
    .addStringOption(o=>o.setName('usuario').setDescription('ID del usuario').setRequired(true)),
  new SlashCommandBuilder().setName('timeout').setDescription('Aplica timeout.')
    .setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers)
    .addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true))
    .addStringOption(o=>o.setName('duracion').setDescription('Ejemplo: 1h, 30m, 1d').setRequired(true))
    .addStringOption(o=>o.setName('razon').setDescription('Razón')),
  new SlashCommandBuilder().setName('untimeout').setDescription('Quita timeout.')
    .setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers)
    .addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)),
  new SlashCommandBuilder().setName('history').setDescription('Historial de moderación.')
    .setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers)
    .addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)),
  new SlashCommandBuilder().setName('clear').setDescription('Elimina mensajes.')
    .setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages)
    .addIntegerOption(o=>o.setName('cantidad').setDescription('Cantidad 1-10000').setMinValue(1).setMaxValue(10000).setRequired(true)),
  new SlashCommandBuilder().setName('logs').setDescription('Configura los logs.')
    .setDefaultMemberPermissions(ADMIN)
    .addSubcommand(s=>s.setName('set').setDescription('Configura el canal de logs.')
      .addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true)))
    .addSubcommand(s=>s.setName('disable').setDescription('Desactiva los logs.'))
    .addSubcommand(s=>s.setName('status').setDescription('Muestra la configuración.')),
  new SlashCommandBuilder().setName('automod').setDescription('Configura AutoMod.')
    .setDefaultMemberPermissions(ADMIN)
    .addSubcommand(s=>s.setName('setup').setDescription('Muestra reglas AutoMod.'))
    .addSubcommand(s=>s.setName('spam').setDescription('Configura anti-spam.')
      .addBooleanOption(o=>o.setName('enabled').setRequired(true))
      .addIntegerOption(o=>o.setName('limit').setMinValue(2).setMaxValue(20).setRequired(true))
      .addStringOption(o=>o.setName('action').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}).addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma'))))
    .addSubcommand(s=>s.setName('links').setDescription('Configura bloqueo de enlaces.')
      .addBooleanOption(o=>o.setName('enabled').setRequired(true))
      .addStringOption(o=>o.setName('whitelist').setDescription('Dominios separados por coma'))
      .addStringOption(o=>o.setName('action').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}).addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma'))))
    .addSubcommand(s=>s.setName('invites').setDescription('Configura bloqueo de invitaciones.')
      .addBooleanOption(o=>o.setName('enabled').setRequired(true))
      .addStringOption(o=>o.setName('action').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}).addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma'))))
    .addSubcommand(s=>s.setName('words').setDescription('Configura palabras prohibidas.')
      .addBooleanOption(o=>o.setName('enabled').setRequired(true))
      .addStringOption(o=>o.setName('words').setDescription('Palabras separadas por coma').setRequired(true))
      .addStringOption(o=>o.setName('action').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}).addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma'))))
    .addSubcommand(s=>s.setName('mentions').setDescription('Configura límite de menciones.')
      .addBooleanOption(o=>o.setName('enabled').setRequired(true))
      .addIntegerOption(o=>o.setName('limit').setMinValue(1).setMaxValue(20).setRequired(true))
      .addStringOption(o=>o.setName('action').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}).addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma'))))
    .addSubcommand(s=>s.setName('caps').setDescription('Configura límite de mayúsculas.')
      .addBooleanOption(o=>o.setName('enabled').setRequired(true))
      .addIntegerOption(o=>o.setName('percentage').setMinValue(50).setMaxValue(100).setRequired(true))
      .addStringOption(o=>o.setName('action').setRequired(true).addChoices({name:'Eliminar',value:'delete'},{name:'Advertir',value:'warn'},{name:'Timeout',value:'timeout'},{name:'Ban',value:'ban'}).addStringOption(o=>o.setName('duracion').setDescription('Duración de timeout, ej. 1h, 6h, 1d, 1w'))
      .addStringOption(o=>o.setName('excepciones').setDescription('IDs de roles/canales excluidos, separados por coma')))),
  new SlashCommandBuilder().setName('giveaway').setDescription('Gestiona sorteos.')
    .setDefaultMemberPermissions(ADMIN)
    .addSubcommand(s=>s.setName('create').setDescription('Crea un sorteo.')
      .addStringOption(o=>o.setName('duracion').setDescription('Ejemplo: 10m, 2h, 1d').setRequired(true))
      .addIntegerOption(o=>o.setName('ganadores').setDescription('Ganadores').setMinValue(1).setMaxValue(20).setRequired(true))
      .addStringOption(o=>o.setName('premio').setDescription('Premio').setMaxLength(256).setRequired(true)))
    .addSubcommand(s=>s.setName('end').setDescription('Finaliza un sorteo.')
      .addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)))
    .addSubcommand(s=>s.setName('reroll').setDescription('Selecciona nuevos ganadores.')
      .addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)))
    .addSubcommand(s=>s.setName('cancel').setDescription('Cancela un sorteo.')
      .addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)))
    .addSubcommand(s=>s.setName('list').setDescription('Lista sorteos activos.')),
  new SlashCommandBuilder().setName('vouches').setDescription('Consulta reputación y vouches.')
    .addSubcommand(s=>s.setName('view').setDescription('Ver perfil de reputación.')
      .addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)))
    .addSubcommand(s=>s.setName('top').setDescription('Top 10 de vouches.'))
    .addSubcommand(s=>s.setName('stats').setDescription('Estadísticas del sistema.')),
  new SlashCommandBuilder().setName('stats').setDescription('Muestra estadísticas.')
    .addSubcommand(s=>s.setName('server').setDescription('Estadísticas del servidor.'))
    .addSubcommand(s=>s.setName('bot').setDescription('Estadísticas de Codek Hub.')),
  new SlashCommandBuilder().setName('config').setDescription('Configuración central.')
    .setDefaultMemberPermissions(ADMIN)
    .addSubcommand(s=>s.setName('status').setDescription('Estado de todos los módulos.'))
    .addSubcommand(s=>s.setName('tickets').setDescription('Estado de tickets.'))
    .addSubcommand(s=>s.setName('welcome').setDescription('Estado de bienvenida.'))
    .addSubcommand(s=>s.setName('logs').setDescription('Estado de logs.'))
    .addSubcommand(s=>s.setName('automod').setDescription('Estado de AutoMod.'))
    .addSubcommand(s=>s.setName('vouches').setDescription('Estado de vouches.')),
  new SlashCommandBuilder().setName('health').setDescription('Estado de salud del bot.'),
  new SlashCommandBuilder().setName('backup').setDescription('Backups de configuración.')
    .setDefaultMemberPermissions(ADMIN)
    .addSubcommand(s=>s.setName('create').setDescription('Crea un backup.'))
    .addSubcommand(s=>s.setName('list').setDescription('Lista backups.'))
    .addSubcommand(s=>s.setName('restore').setDescription('Restaura configuración desde un backup.')
      .addStringOption(o=>o.setName('archivo').setDescription('Nombre del archivo de backup').setRequired(true))
      .addBooleanOption(o=>o.setName('confirmar').setDescription('Confirma la restauración').setRequired(true)))
  ];
