import {Client,GatewayIntentBits,Events,SlashCommandBuilder,REST,Routes,PermissionFlagsBits,ChannelType,ActionRowBuilder,StringSelectMenuBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,ActivityType} from 'discord.js';
import {loadEnvironment,logger,renderVariables,prisma,ensureGuild,findAutoResponder,audit} from '../../../packages/shared/src/index.js';
const env=loadEnvironment();
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildPresences]});
const cooldowns=new Map(), locks=new Set();
const admin=PermissionFlagsBits.Administrator;
const commands=[
new SlashCommandBuilder().setName('tickets').setDescription('Configura tickets.').setDefaultMemberPermissions(admin).addSubcommand(s=>s.setName('panel').setDescription('Crea un panel.').addStringOption(o=>o.setName('nombre').setDescription('Nombre').setRequired(true)).addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true))).addSubcommand(s=>s.setName('categoria').setDescription('Añade categoría.').addStringOption(o=>o.setName('panel').setDescription('ID del panel').setRequired(true)).addStringOption(o=>o.setName('nombre').setDescription('Nombre').setRequired(true)).addRoleOption(o=>o.setName('staff').setDescription('Rol soporte').setRequired(true)).addStringOption(o=>o.setName('emoji').setDescription('Emoji').setRequired(false))).addSubcommand(s=>s.setName('publicar').setDescription('Publica panel.').addStringOption(o=>o.setName('panel').setDescription('ID').setRequired(true))),
new SlashCommandBuilder().setName('welcome').setDescription('Configura bienvenida.').setDefaultMemberPermissions(admin).addSubcommand(s=>s.setName('set').setDescription('Configura.').addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true)).addStringOption(o=>o.setName('mensaje').setDescription('Mensaje').setRequired(true))),
new SlashCommandBuilder().setName('vouch-config').setDescription('Configura vouches.').setDefaultMemberPermissions(admin).addSubcommand(s=>s.setName('set').setDescription('Activa vouches.').addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true)).addRoleOption(o=>o.setName('rol').setDescription('Rol permitido').setRequired(false)).addIntegerOption(o=>o.setName('cooldown').setDescription('Segundos').setMinValue(0).setRequired(false))).addSubcommand(s=>s.setName('reset').setDescription('Desactiva vouches.')),
new SlashCommandBuilder().setName('vouch').setDescription('Deja una reseña.').addUserOption(o=>o.setName('member').setDescription('Miembro').setRequired(true)).addStringOption(o=>o.setName('tipo').setDescription('Tipo').setRequired(true).addChoices({name:'Legit',value:'Legit'},{name:'No Legit',value:'No Legit'})).addIntegerOption(o=>o.setName('rating').setDescription('1-5').setRequired(true).setMinValue(1).setMaxValue(5)),
new SlashCommandBuilder().setName('autoresponder').setDescription('Gestiona respuestas.').setDefaultMemberPermissions(admin).addSubcommand(s=>s.setName('add').setDescription('Añade.').addStringOption(o=>o.setName('trigger').setDescription('Trigger').setRequired(true)).addStringOption(o=>o.setName('respuesta').setDescription('Respuesta').setRequired(true)).addStringOption(o=>o.setName('modo').setDescription('Modo').addChoices({name:'Contiene',value:'contains'},{name:'Exacta',value:'exact'}).setRequired(false))).addSubcommand(s=>s.setName('remove').setDescription('Elimina.').addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('Lista.')),
new SlashCommandBuilder().setName('presence').setDescription('Rich Presence del bot.').setDefaultMemberPermissions(admin).addSubcommand(s=>s.setName('set').setDescription('Configura.').addStringOption(o=>o.setName('tipo').setDescription('Tipo').setRequired(true).addChoices({name:'Playing',value:'Playing'},{name:'Watching',value:'Watching'},{name:'Listening',value:'Listening'},{name:'Streaming',value:'Streaming'})).addStringOption(o=>o.setName('texto').setDescription('Texto').setRequired(true))).addSubcommand(s=>s.setName('reset').setDescription('Restablece.')),
new SlashCommandBuilder().setName('variables').setDescription('Muestra variables.')
];
const e=c=>({content:c,flags:64});
const color=x=>{const n=parseInt(String(x||'5865F2').replace('#',''),16);return Number.isFinite(n)?n:0x5865F2};
async function deploy(){const rest=new REST({version:'10'}).setToken(env.DISCORD_TOKEN);const route=env.DEV_GUILD_ID?Routes.applicationGuildCommands(env.DISCORD_CLIENT_ID,env.DEV_GUILD_ID):Routes.applicationCommands(env.DISCORD_CLIENT_ID);await rest.put(route,{body:commands.map(x=>x.toJSON())});}
async function presence(){const p=await prisma.presenceConfig.findFirst({where:{enabled:true},orderBy:{updatedAt:'desc'}});if(!p)return client.user.setPresence({activities:[],status:'online'});const t={Playing:ActivityType.Playing,Watching:ActivityType.Watching,Listening:ActivityType.Listening,Streaming:ActivityType.Streaming};client.user.setPresence({activities:[{name:p.text,type:t[p.type]??ActivityType.Watching}],status:'online'});}
async function createTicket(i,cat){const key=i.guildId+':'+cat.id+':'+i.user.id;if(locks.has(key))return i.reply(e('Ya se está creando tu ticket.'));locks.add(key);try{const old=await prisma.ticket.findFirst({where:{guildId:i.guildId,categoryId:cat.id,userId:i.user.id,status:'open'}});if(old)return i.reply(e('Ya tienes un ticket abierto para esta categoría.'));const n=(await prisma.ticket.count({where:{guildId:i.guildId,categoryId:cat.id}}))+1;const overwrites=[{id:i.guild.roles.everyone.id,deny:['ViewChannel']},{id:i.user.id,allow:['ViewChannel','SendMessages','ReadMessageHistory']}];for(const id of cat.supportRoleIds)overwrites.push({id,allow:['ViewChannel','SendMessages','ReadMessageHistory']});const ch=await i.guild.channels.create({name:('ticket-'+n),type:ChannelType.GuildText,parent:cat.discordCategoryId||undefined,permissionOverwrites:overwrites});const t=await prisma.ticket.create({data:{guildId:i.guildId,categoryId:cat.id,userId:i.user.id,channelId:ch.id,number:n}});const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:claim:'+t.id).setLabel('Reclamar').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('ticket:close:'+t.id).setLabel('Cerrar ticket').setStyle(ButtonStyle.Danger));await ch.send({content:i.user.toString()+' '+cat.supportRoleIds.map(x=>'<@&'+x+'>').join(' '),embeds:[new EmbedBuilder().setTitle('Ticket • '+cat.name).setDescription(cat.description||'El equipo te atenderá pronto.').setColor(0x5865F2).setTimestamp()],components:[row]});await audit(i.guildId,i.user.id,'tickets','created',t.id);return i.reply(e('Ticket creado: '+ch));}finally{locks.delete(key);}}
async function closeTicket(i,t){if(!t)return i.reply(e('Ticket no encontrado.'));const msgs=[...await i.channel.messages.fetch({limit:100}).then(x=>[...x.values()])].reverse();const esc=x=>String(x??'').replace(/[&<>]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[s]));const html='<html><body><h1>Ticket #'+t.number+'</h1>'+msgs.map(m=>'<p><b>'+esc(m.author.tag)+'</b> '+esc(m.content)+'</p>').join('')+'</body></html>';await prisma.ticket.update({where:{id:t.id},data:{status:'closed',closedAt:new Date()}});await prisma.ticketTranscript.upsert({where:{ticketId:t.id},update:{html},create:{ticketId:t.id,html}});await audit(i.guildId,i.user.id,'tickets','closed',t.id);await i.reply(e('Ticket cerrado.'));setTimeout(()=>i.channel.delete().catch(()=>{}),2500);}
client.once(Events.ClientReady,async c=>{await Promise.all(c.guilds.cache.map(g=>ensureGuild(g).catch(()=>null)));await deploy();await presence();logger.info('Codek Hub conectado',{user:c.user.tag,guilds:c.guilds.cache.size});});
client.on(Events.GuildCreate,g=>ensureGuild(g).catch(()=>{}));
client.on(Events.GuildMemberAdd,async m=>{const c=await prisma.welcomeConfig.findUnique({where:{guildId:m.guild.id}}).catch(()=>null);if(!c?.enabled||!c.channelId)return;const ch=m.guild.channels.cache.get(c.channelId);if(!ch?.isTextBased())return;const ctx={user:m.user.toString(),username:m.user.username,displayname:m.displayName,userid:m.id,server:m.guild.name,membercount:m.guild.memberCount};await ch.send({content:renderVariables(c.message||'¡Bienvenido {user} a {server}!',ctx),embeds:c.title||c.description?[new EmbedBuilder().setTitle(c.title||'Bienvenido').setDescription(renderVariables(c.description||'',ctx)).setColor(color(c.color)).setTimestamp()]:[]}).catch(()=>{});});
client.on(Events.MessageCreate,async m=>{if(m.author.bot||!m.guildId)return;const r=await findAutoResponder(m.content,m.guildId).catch(()=>null);if(!r||!String(r.response).trim())return;const out=renderVariables(r.response,{user:m.author.toString(),username:m.author.username,displayname:m.member?.displayName,userid:m.author.id,server:m.guild.name,membercount:m.guild.memberCount,channel:m.channel.toString(),channelname:m.channel.name});if(out.trim())await m.reply(out).catch(()=>{});});
client.on(Events.InteractionCreate,async i=>{try{if(i.isStringSelectMenu()&&i.customId.startsWith('ticket:select:')){const c=await prisma.ticketCategory.findUnique({where:{id:i.values[0]}});if(c)return createTicket(i,c);}if(i.isButton()&&i.customId.startsWith('ticket:claim:')){const id=i.customId.split(':')[2];const t=await prisma.ticket.findUnique({where:{id}});if(!t)return i.reply(e('Ticket no encontrado.'));await prisma.ticket.update({where:{id},data:{claimedById:i.user.id}});return i.reply(e('Ticket reclamado.'));}if(i.isButton()&&i.customId.startsWith('ticket:close:')){const id=i.customId.split(':')[2];const t=await prisma.ticket.findUnique({where:{id},include:{category:true}});return closeTicket(i,t);}if(i.isModalSubmit()&&i.customId.startsWith('vouch:')){const [,targetId,type,rating]=i.customId.split(':');const text=i.fields.getTextInputValue('review').trim();if(!text)return i.reply(e('La reseña no puede estar vacía.'));const cfg=await prisma.vouchConfig.findUnique({where:{guildId:i.guildId}});if(!cfg?.enabled)return i.reply(e('Vouches desactivados.'));await prisma.vouch.create({data:{guildId:i.guildId,targetId,reviewerId:i.user.id,reviewType:type,rating:Number(rating),text}});const ch=i.guild.channels.cache.get(cfg.channelId);if(ch?.isTextBased())await ch.send({embeds:[new EmbedBuilder().setTitle(cfg.title||'Nueva reseña').setDescription(cfg.description||'').setColor(color(cfg.color)).setThumbnail((await i.guild.members.fetch(targetId)).displayAvatarURL()).addFields({name:'Usuario',value:'<@'+targetId+'>',inline:true},{name:'Tipo',value:type,inline:true},{name:'Rating',value:'⭐'.repeat(Number(rating)),inline:true},{name:'Reseña',value:text}).setTimestamp()]});cooldowns.set(i.guildId+':'+i.user.id,Date.now());return i.reply(e('¡Vouch registrado!'));}if(!i.isChatInputCommand())return;
if(i.commandName==='variables')return i.reply(e('{user} {username} {displayname} {userid} {server} {membercount} {channel} {channelname} {ticket} {category} {staff}'));
if(i.commandName==='welcome'){const ch=i.options.getChannel('canal'),msg=i.options.getString('mensaje');await prisma.welcomeConfig.upsert({where:{guildId:i.guildId},update:{enabled:true,channelId:ch.id,message:msg},create:{guildId:i.guildId,enabled:true,channelId:ch.id,message:msg}});return i.reply(e('Bienvenida configurada.'));}
if(i.commandName==='vouch-config'){if(i.options.getSubcommand()==='reset'){await prisma.vouchConfig.upsert({where:{guildId:i.guildId},update:{enabled:false},create:{guildId:i.guildId,enabled:false,allowedRoleIds:[]}});return i.reply(e('Vouches desactivados.'));}const ch=i.options.getChannel('canal'),role=i.options.getRole('rol'),cool=i.options.getInteger('cooldown')??60;await prisma.vouchConfig.upsert({where:{guildId:i.guildId},update:{enabled:true,channelId:ch.id,allowedRoleIds:role?[role.id]:[],cooldown:cool},create:{guildId:i.guildId,enabled:true,channelId:ch.id,allowedRoleIds:role?[role.id]:[],cooldown:cool}});return i.reply(e('Vouches configurados.'));}
if(i.commandName==='vouch'){const cfg=await prisma.vouchConfig.findUnique({where:{guildId:i.guildId}});if(!cfg?.enabled)return i.reply(e('Vouches desactivados.'));const last=cooldowns.get(i.guildId+':'+i.user.id)||0;if(Date.now()-last<cfg.cooldown*1000)return i.reply(e('Espera antes de enviar otro vouch.'));if(cfg.allowedRoleIds.length&&!cfg.allowedRoleIds.some(x=>i.member.roles.cache.has(x)))return i.reply(e('No tienes permiso para usar /vouch.'));const target=i.options.getUser('member'),type=i.options.getString('tipo'),rating=i.options.getInteger('rating');if(target.id===i.user.id)return i.reply(e('No puedes votarte a ti mismo.'));const modal=new ModalBuilder().setCustomId('vouch:'+target.id+':'+type+':'+rating).setTitle('Danos tu reseña');modal.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('review').setLabel('Danos tu reseña').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(1000)));return i.showModal(modal);}
if(i.commandName==='autoresponder'){const sub=i.options.getSubcommand();if(sub==='add'){await prisma.autoResponder.create({data:{guildId:i.guildId,trigger:i.options.getString('trigger'),response:i.options.getString('respuesta'),matchType:i.options.getString('modo')||'contains'}});return i.reply(e('Autoresponder creado.'));}if(sub==='remove'){await prisma.autoResponder.delete({where:{id:i.options.getString('id')}}).catch(()=>{});return i.reply(e('Autoresponder eliminado si existía.'));}const rows=await prisma.autoResponder.findMany({where:{guildId:i.guildId}});return i.reply(e(rows.length?rows.map(r=>r.id+' • '+r.trigger+' • '+r.matchType).join('\n'):'No hay autoresponders.'));}
if(i.commandName==='presence'){if(i.options.getSubcommand()==='reset'){await prisma.presenceConfig.updateMany({data:{enabled:false}});await presence();return i.reply(e('Rich Presence restablecida.'));}await prisma.presenceConfig.updateMany({data:{enabled:false}});await prisma.presenceConfig.upsert({where:{guildId:i.guildId},update:{enabled:true,type:i.options.getString('tipo'),text:i.options.getString('texto')},create:{guildId:i.guildId,enabled:true,type:i.options.getString('tipo'),text:i.options.getString('texto')}});await presence();return i.reply(e('Rich Presence actualizada.'));}
if(i.commandName==='tickets'){const sub=i.options.getSubcommand();if(sub==='panel'){const p=await prisma.ticketPanel.create({data:{guildId:i.guildId,name:i.options.getString('nombre'),channelId:i.options.getChannel('canal').id}});return i.reply(e('Panel creado. ID: '+p.id));}if(sub==='categoria'){const p=await prisma.ticketPanel.findFirst({where:{id:i.options.getString('panel'),guildId:i.guildId}});if(!p)return i.reply(e('Panel no encontrado.'));const c=await prisma.ticketCategory.create({data:{panelId:p.id,name:i.options.getString('nombre'),emoji:i.options.getString('emoji'),supportRoleIds:[i.options.getRole('staff').id]}});return i.reply(e('Categoría creada. ID: '+c.id));}const p=await prisma.ticketPanel.findFirst({where:{id:i.options.getString('panel'),guildId:i.guildId},include:{categories:true}});if(!p||!p.categories.length)return i.reply(e('Panel o categorías no encontrados.'));const ch=i.guild.channels.cache.get(p.channelId);if(!ch?.isTextBased())return i.reply(e('Canal no encontrado.'));const menu=new StringSelectMenuBuilder().setCustomId('ticket:select:'+p.id).setPlaceholder('Selecciona una categoría').addOptions(p.categories.slice(0,25).map(c=>({label:c.name.slice(0,100),value:c.id,description:(c.description||'Abrir ticket').slice(0,100),emoji:c.emoji||undefined})));return ch.send({embeds:[new EmbedBuilder().setTitle(p.title||p.name).setDescription(p.description||'Selecciona una categoría.').setColor(color(p.color))],components:[new ActionRowBuilder().addComponents(menu)]}).then(()=>i.reply(e('Panel publicado.')));}
}catch(err){logger.error('Interaction error',{error:err.message});if(!i.replied&&!i.deferred)await i.reply(e('Ocurrió un error.'));}});
client.login(env.DISCORD_TOKEN).catch(err=>{logger.error('Discord login failed',{error:err.message});process.exit(1);});