import {
 Client, GatewayIntentBits, Events, SlashCommandBuilder, REST, Routes,
 PermissionFlagsBits, ChannelType, ActionRowBuilder, StringSelectMenuBuilder,
 ButtonBuilder, ButtonStyle, EmbedBuilder, ModalBuilder, TextInputBuilder,
 TextInputStyle, ActivityType
} from 'discord.js';
import { loadEnvironment, logger, renderVariables, prisma, ensureGuild, findAutoResponder, audit } from '../../../packages/shared/src/index.js';

const env = loadEnvironment();
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent] });
const cooldowns = new Map();
const locks = new Set();
const closeLocks = new Set();
const ADMIN = PermissionFlagsBits.Administrator;

const commands = [
 new SlashCommandBuilder().setName('tickets').setDescription('Configura tickets.').setDefaultMemberPermissions(ADMIN)
  .addSubcommand(s=>s.setName('panel').setDescription('Crea un panel.').addStringOption(o=>o.setName('nombre').setDescription('Nombre').setRequired(true)).addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true)).addStringOption(o=>o.setName('titulo').setDescription('Título')).addStringOption(o=>o.setName('descripcion').setDescription('Descripción')).addStringOption(o=>o.setName('color').setDescription('Color HEX')).addStringOption(o=>o.setName('imagen').setDescription('URL imagen')).addStringOption(o=>o.setName('thumbnail').setDescription('URL thumbnail')).addStringOption(o=>o.setName('footer').setDescription('Footer')))
  .addSubcommand(s=>s.setName('categoria').setDescription('Añade categoría.').addStringOption(o=>o.setName('panel').setDescription('ID panel').setRequired(true)).addStringOption(o=>o.setName('nombre').setDescription('Nombre').setRequired(true)).addStringOption(o=>o.setName('staff').setDescription('Roles separados por comas').setRequired(true)).addStringOption(o=>o.setName('emoji').setDescription('Emoji')).addStringOption(o=>o.setName('descripcion').setDescription('Descripción')).addChannelOption(o=>o.setName('categoria-canal').setDescription('Categoría Discord').addChannelTypes(ChannelType.GuildCategory)))
  .addSubcommand(s=>s.setName('pregunta').setDescription('Añade pregunta.').addStringOption(o=>o.setName('categoria').setDescription('ID categoría').setRequired(true)).addStringOption(o=>o.setName('label').setDescription('Pregunta').setRequired(true)).addStringOption(o=>o.setName('placeholder').setDescription('Placeholder')).addBooleanOption(o=>o.setName('obligatoria').setDescription('Obligatoria')))
  .addSubcommand(s=>s.setName('publicar').setDescription('Publica panel.').addStringOption(o=>o.setName('panel').setDescription('ID panel').setRequired(true)))
  .addSubcommand(s=>s.setName('log').setDescription('Configura logs.').addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true))),
 new SlashCommandBuilder().setName('welcome').setDescription('Configura bienvenida.').setDefaultMemberPermissions(ADMIN).addSubcommand(s=>s.setName('set').setDescription('Configura.').addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true)).addStringOption(o=>o.setName('mensaje').setDescription('Mensaje').setRequired(true)).addStringOption(o=>o.setName('titulo').setDescription('Título')).addStringOption(o=>o.setName('descripcion').setDescription('Descripción')).addStringOption(o=>o.setName('color').setDescription('Color HEX')).addStringOption(o=>o.setName('imagen').setDescription('URL imagen')).addStringOption(o=>o.setName('thumbnail').setDescription('URL thumbnail')).addStringOption(o=>o.setName('footer').setDescription('Footer'))),
 new SlashCommandBuilder().setName('vouch-config').setDescription('Configura vouches.').setDefaultMemberPermissions(ADMIN).addSubcommand(s=>s.setName('set').setDescription('Activa.').addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true)).addStringOption(o=>o.setName('roles').setDescription('Roles separados por comas')).addIntegerOption(o=>o.setName('cooldown').setDescription('Segundos').setMinValue(0)).addStringOption(o=>o.setName('titulo').setDescription('Título')).addStringOption(o=>o.setName('descripcion').setDescription('Descripción')).addStringOption(o=>o.setName('color').setDescription('Color HEX')).addStringOption(o=>o.setName('imagen').setDescription('URL imagen')).addStringOption(o=>o.setName('thumbnail').setDescription('URL thumbnail')).addStringOption(o=>o.setName('footer').setDescription('Footer'))).addSubcommand(s=>s.setName('reset').setDescription('Desactiva.')),
 new SlashCommandBuilder().setName('vouch').setDescription('Deja una reseña.').addUserOption(o=>o.setName('member').setDescription('Miembro').setRequired(true)).addStringOption(o=>o.setName('tipo').setDescription('Tipo').setRequired(true).addChoices({name:'Legit',value:'Legit'},{name:'No Legit',value:'No Legit'})).addIntegerOption(o=>o.setName('rating').setDescription('1-5').setRequired(true).setMinValue(1).setMaxValue(5)),
 new SlashCommandBuilder().setName('autoresponder').setDescription('Gestiona respuestas.').setDefaultMemberPermissions(ADMIN).addSubcommand(s=>s.setName('add').setDescription('Añade.').addStringOption(o=>o.setName('trigger').setDescription('Trigger').setRequired(true)).addStringOption(o=>o.setName('respuesta').setDescription('Respuesta').setRequired(true)).addStringOption(o=>o.setName('modo').setDescription('Modo').addChoices({name:'Contiene',value:'contains'},{name:'Exacta',value:'exact'})).addStringOption(o=>o.setName('titulo').setDescription('Título embed')).addStringOption(o=>o.setName('descripcion').setDescription('Descripción embed')).addStringOption(o=>o.setName('color').setDescription('Color HEX'))).addSubcommand(s=>s.setName('remove').setDescription('Elimina.').addStringOption(o=>o.setName('trigger').setDescription('Trigger').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('Lista.')),
 new SlashCommandBuilder().setName('presence').setDescription('Rich Presence del bot.').setDefaultMemberPermissions(ADMIN).addSubcommand(s=>s.setName('set').setDescription('Configura.').addStringOption(o=>o.setName('tipo').setDescription('Tipo').setRequired(true).addChoices({name:'Playing',value:'Playing'},{name:'Watching',value:'Watching'},{name:'Listening',value:'Listening'})).addStringOption(o=>o.setName('texto').setDescription('Texto').setRequired(true))).addSubcommand(s=>s.setName('reset').setDescription('Restablece.')),
 new SlashCommandBuilder().setName('variables').setDescription('Muestra variables.')
];

const deny = c => ({content:c,flags:64});
const color = v => { const h=String(v||'5865F2').replace(/^#/,'').trim(); return /^[0-9a-fA-F]{6}$/.test(h)?parseInt(h,16):0x5865F2; };
const isAdmin = i => Boolean(i.memberPermissions?.has(ADMIN));
const roleIds = (g,v) => String(v||'').split(',').map(x=>x.trim().replace(/[<@&>]/g,'')).filter(id=>g.roles.cache.has(id));
const clean = v => String(v||'ticket').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,45)||'ticket';
const context = (u,g,ch) => ({user:u.toString(),username:u.username,displayname:u.globalName||u.displayName||u.username,userid:u.id,server:g.name,membercount:g.memberCount,channel:ch?.toString?.()||'channel',channelname:ch?.name||'channel'});
async function logToChannel(g,title,description){ try { const x=await prisma.guild.findUnique({where:{id:g.id},select:{logChannelId:true}}); const ch=x?.logChannelId?g.channels.cache.get(x.logChannelId):null; if(ch?.isTextBased()) await ch.send({embeds:[new EmbedBuilder().setTitle(title).setDescription(description).setColor(0x5865F2).setTimestamp()]}); } catch(e){ logger.warn('Log failed',{error:e.message}); } }
async function nextNumber(guildId,categoryId){ return prisma.$transaction(async tx=>{ const k='codek:'+guildId+':'+categoryId; await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${k}))`; const last=await tx.ticket.findFirst({where:{guildId,categoryId},orderBy:{number:'desc'},select:{number:true}}); return (last?.number||0)+1; }); }
async function presence(){ const p=await prisma.presenceConfig.findFirst({where:{enabled:true},orderBy:{updatedAt:'desc'}}); if(!p)return client.user.setPresence({activities:[],status:'online'}); const t={Playing:ActivityType.Playing,Watching:ActivityType.Watching,Listening:ActivityType.Listening}; client.user.setPresence({activities:[{name:p.text,type:t[p.type]||ActivityType.Watching}],status:'online'}); }
async function deploy(){ const rest=new REST({version:'10'}).setToken(env.DISCORD_TOKEN); const route=env.DEV_GUILD_ID?Routes.applicationGuildCommands(env.DISCORD_CLIENT_ID,env.DEV_GUILD_ID):Routes.applicationCommands(env.DISCORD_CLIENT_ID); await rest.put(route,{body:commands.map(c=>c.toJSON())}); }
async function createTicket(i,cat,answers=[]){ const key=i.guildId+':'+cat.id+':'+i.user.id; if(locks.has(key))return i.reply(deny('Ya se está creando tu ticket.')); locks.add(key); try { const old=await prisma.ticket.findFirst({where:{guildId:i.guildId,categoryId:cat.id,userId:i.user.id,status:'open'}}); if(old)return i.reply(deny('Ya tienes un ticket abierto para esta categoría.')); const n=await nextNumber(i.guildId,cat.id); const overwrites=[{id:i.guild.roles.everyone.id,deny:['ViewChannel']},{id:i.user.id,allow:['ViewChannel','SendMessages','ReadMessageHistory']},...cat.supportRoleIds.map(id=>({id,allow:['ViewChannel','SendMessages','ReadMessageHistory']}))]; const ch=await i.guild.channels.create({name:clean(cat.name)+'-'+n,type:ChannelType.GuildText,parent:cat.discordCategoryId||undefined,permissionOverwrites:overwrites}); const t=await prisma.ticket.create({data:{guildId:i.guildId,categoryId:cat.id,userId:i.user.id,channelId:ch.id,number:n,answers:answers.length?{create:answers}:undefined}}); const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:claim:'+t.id).setLabel('Reclamar').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('ticket:close:'+t.id).setLabel('Cerrar ticket').setStyle(ButtonStyle.Danger)); const a=answers.length?'\n\n'+answers.map(x=>'**'+x.label+':** '+x.answer).join('\n'):''; await ch.send({content:i.user.toString()+' '+cat.supportRoleIds.map(x=>'<@&'+x+'>').join(' '),embeds:[new EmbedBuilder().setTitle('Ticket • '+cat.name).setDescription((cat.description||'El equipo te atenderá pronto.')+a).setColor(0x5865F2).setTimestamp()],components:[row]}); await audit(i.guildId,i.user.id,'tickets','created','#'+n); await logToChannel(i.guild,'Ticket creado','<@'+i.user.id+'> creó **'+cat.name+' #'+n+'**.'); return i.reply(deny('Ticket creado: '+ch)); } catch(e){ logger.error('Ticket creation failed',{error:e.message}); return i.reply(deny('No se pudo crear el ticket.')); } finally { locks.delete(key); } }
async function transcript(ch,t){ const xs=[...await ch.messages.fetch({limit:100})].reverse(); const esc=x=>String(x||'').replace(/[&<>]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[s])); return '<!doctype html><html><body><h1>Ticket #'+t.number+'</h1><p>Usuario: '+esc(t.userId)+'<br>Categoría: '+esc(t.category.name)+'<br>Creado: '+t.createdAt.toISOString()+'</p>'+xs.map(m=>'<p><b>'+esc(m.author.tag)+'</b> '+new Date(m.createdTimestamp).toISOString()+'<br>'+esc(m.content||'[embed/archivo]')+'</p>').join('')+'</body></html>'; }
async function closeTicket(i,t){ if(closeLocks.has(t.id))return i.reply(deny('El cierre ya está en proceso.')); closeLocks.add(t.id); try { const html=await transcript(i.channel,t); await prisma.ticket.update({where:{id:t.id},data:{status:'closed',closedAt:new Date(),transcript:{upsert:{update:{html},create:{html}}}}}); await audit(i.guildId,i.user.id,'tickets','closed','#'+t.number); await logToChannel(i.guild,'Ticket cerrado','Ticket **#'+t.number+'** cerrado por <@'+i.user.id+'>.'); const g=await prisma.guild.findUnique({where:{id:i.guildId},select:{logChannelId:true}}); const lc=g?.logChannelId?i.guild.channels.cache.get(g.logChannelId):null; if(lc?.isTextBased())await lc.send({content:'Transcripción del ticket #'+t.number,files:[{attachment:Buffer.from(html,'utf8'),name:'ticket-'+t.number+'.html'}]}); await i.reply(deny('Ticket cerrado. Transcripción guardada.')); setTimeout(()=>i.channel.delete().catch(()=>{}),2500); } catch(e){ logger.error('Ticket close failed',{error:e.message}); if(!i.replied)await i.reply(deny('No se pudo cerrar el ticket.')); } finally { closeLocks.delete(t.id); } }

client.once(Events.ClientReady,async c=>{ try { await prisma.$queryRaw`SELECT 1`; for(const g of c.guilds.cache.values())await ensureGuild(g); await deploy(); await presence(); logger.info('Codek Hub conectado',{user:c.user.tag,guilds:c.guilds.cache.size}); } catch(e){ logger.error('Startup failed',{error:e.message}); process.exit(1); } });
client.on(Events.GuildCreate,g=>ensureGuild(g).catch(()=>{}));
client.on(Events.GuildMemberAdd,async m=>{ try { const c=await prisma.welcomeConfig.findUnique({where:{guildId:m.guild.id}}); if(!c?.enabled||!c.channelId)return; const ch=m.guild.channels.cache.get(c.channelId); if(!ch?.isTextBased())return; const x=context(m.user,m.guild,ch); const emb=new EmbedBuilder().setTitle(renderVariables(c.title||'¡Bienvenido!',x)).setDescription(renderVariables(c.description||'',x)).setColor(color(c.color)).setTimestamp(); if(c.image)emb.setImage(renderVariables(c.image,x)); if(c.thumbnail)emb.setThumbnail(renderVariables(c.thumbnail,x)); if(c.footer)emb.setFooter({text:renderVariables(c.footer,x)}); await ch.send({content:renderVariables(c.message||'¡Bienvenido {user} a {server}!',x),embeds:[emb]}); await audit(m.guild.id,m.id,'welcome','sent',ch.id); } catch(e){logger.error('Welcome failed',{error:e.message});} });
client.on(Events.MessageCreate,async m=>{ if(m.author.bot||!m.guildId)return; try { const r=await findAutoResponder(m.content,m.guildId); if(!r||!r.response?.trim())return; const x=context(m.author,m.guild,m.channel); const payload={content:renderVariables(r.response,x)}; if(r.embedTitle||r.embedDescription)payload.embeds=[new EmbedBuilder().setTitle(renderVariables(r.embedTitle||'',x)).setDescription(renderVariables(r.embedDescription||r.response,x)).setColor(color(r.embedColor)).setTimestamp()]; await m.reply(payload); await audit(m.guildId,m.author.id,'autoresponder','used',r.trigger); } catch(e){logger.error('Autoresponder failed',{error:e.message});} });

client.on(Events.InteractionCreate,async i=>{ try {
 if(i.isStringSelectMenu()&&i.customId.startsWith('ticket:select:')){ const c=await prisma.ticketCategory.findUnique({where:{id:i.values[0]},include:{questions:true}}); if(!c)return i.reply(deny('La categoría ya no existe.')); if(c.questions.length>5)return i.reply(deny('Máximo 5 preguntas por categoría.')); if(!c.questions.length)return createTicket(i,c); const modal=new ModalBuilder().setCustomId('ticket:form:'+c.id).setTitle(('Ticket • '+c.name).slice(0,45)); for(const q of c.questions)modal.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(q.id).setLabel(q.label.slice(0,45)).setPlaceholder((q.placeholder||'Respuesta').slice(0,100)).setStyle(TextInputStyle.Paragraph).setRequired(q.required).setMaxLength(1000))); return i.showModal(modal); }
 if(i.isButton()&&i.customId.startsWith('ticket:claim:')){ const id=i.customId.split(':')[2],t=await prisma.ticket.findUnique({where:{id},include:{category:true}}); if(!t||t.status!=='open')return i.reply(deny('Ticket no encontrado o cerrado.')); if(!t.category.supportRoleIds.some(x=>i.member.roles.cache.has(x)))return i.reply(deny('Solo soporte puede reclamar tickets.')); await prisma.ticket.update({where:{id},data:{claimedById:i.user.id}}); await prisma.ticketClaim.create({data:{ticketId:id,userId:i.user.id}}); return i.reply(deny('Ticket reclamado por '+i.user.toString()+'.')); }
 if(i.isButton()&&i.customId.startsWith('ticket:close:')){ const id=i.customId.split(':')[2],t=await prisma.ticket.findUnique({where:{id},include:{category:true}}); if(!t||t.status!=='open')return i.reply(deny('Ticket no encontrado o cerrado.')); const allowed=i.user.id===t.userId||t.category.supportRoleIds.some(x=>i.member.roles.cache.has(x)); if(!allowed)return i.reply(deny('No tienes permiso para cerrar este ticket.')); const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:confirm:'+id).setLabel('Confirmar cierre').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('ticket:cancel:'+id).setLabel('Cancelar').setStyle(ButtonStyle.Secondary)); return i.reply({content:'¿Seguro que quieres cerrar este ticket?',components:[row],flags:64}); }
 if(i.isButton()&&i.customId.startsWith('ticket:cancel:'))return i.update({content:'Cierre cancelado.',components:[]});
 if(i.isButton()&&i.customId.startsWith('ticket:confirm:')){ const id=i.customId.split(':')[2],t=await prisma.ticket.findUnique({where:{id},include:{category:true}}); if(!t)return i.reply(deny('Ticket no encontrado.')); return closeTicket(i,t); }
 if(i.isModalSubmit()&&i.customId.startsWith('ticket:form:')){ const id=i.customId.split(':')[2],c=await prisma.ticketCategory.findUnique({where:{id},include:{questions:true}}); if(!c)return i.reply(deny('Categoría no encontrada.')); const a=c.questions.slice(0,5).map(q=>({label:q.label,answer:i.fields.getTextInputValue(q.id)})); return createTicket(i,c,a); }
 if(i.isModalSubmit()&&i.customId.startsWith('vouch:')){ const [,targetId,type,ratingRaw]=i.customId.split(':'),rating=Number(ratingRaw),text=i.fields.getTextInputValue('review').trim(); if(!text)return i.reply(deny('La reseña no puede estar vacía.')); const c=await prisma.vouchConfig.findUnique({where:{guildId:i.guildId}}); if(!c?.enabled)return i.reply(deny('Vouches desactivados.')); if(c.allowedRoleIds.length&&!c.allowedRoleIds.some(x=>i.member.roles.cache.has(x)))return i.reply(deny('No tienes permiso para usar /vouch.')); const last=cooldowns.get(i.guildId+':'+i.user.id)||0; if(Date.now()-last<c.cooldown*1000)return i.reply(deny('Espera antes de enviar otro vouch.')); const target=await client.users.fetch(targetId).catch(()=>null),ch=c.channelId?i.guild.channels.cache.get(c.channelId):null; if(!target||!ch?.isTextBased())return i.reply(deny('El usuario o canal de vouches ya no existe.')); await prisma.vouch.create({data:{guildId:i.guildId,targetId,reviewerId:i.user.id,reviewType:type,rating,text}}); const x=context(target,i.guild,ch); const emb=new EmbedBuilder().setTitle(renderVariables(c.title||'Nueva reseña',x)).setDescription(renderVariables(c.description||'',x)).setColor(color(c.color)).setThumbnail(target.displayAvatarURL()).addFields({name:'Usuario',value:target.toString(),inline:true},{name:'Tipo',value:type,inline:true},{name:'Rating',value:'⭐'.repeat(rating),inline:true},{name:'Reseña',value:text.slice(0,1024)}).setTimestamp(); if(c.image)emb.setImage(renderVariables(c.image,x)); if(c.footer)emb.setFooter({text:renderVariables(c.footer,x)}); await ch.send({embeds:[emb]}); cooldowns.set(i.guildId+':'+i.user.id,Date.now()); await audit(i.guildId,i.user.id,'vouch','created',targetId); return i.reply(deny('¡Vouch registrado correctamente!')); }
 if(!i.isChatInputCommand())return;
 if(i.commandName==='variables')return i.reply(deny('{user} {username} {displayname} {userid} {server} {membercount} {channel} {channelname} {ticket} {category} {staff}'));
 if(i.commandName==='welcome'){ if(!isAdmin(i))return i.reply(deny('Necesitas permisos de administrador.')); const ch=i.options.getChannel('canal'),msg=i.options.getString('mensaje'); await prisma.welcomeConfig.upsert({where:{guildId:i.guildId},update:{enabled:true,channelId:ch.id,message:msg,title:i.options.getString('titulo'),description:i.options.getString('descripcion'),color:i.options.getString('color'),image:i.options.getString('imagen'),thumbnail:i.options.getString('thumbnail'),footer:i.options.getString('footer')},create:{guildId:i.guildId,enabled:true,channelId:ch.id,message:msg,title:i.options.getString('titulo'),description:i.options.getString('descripcion'),color:i.options.getString('color'),image:i.options.getString('imagen'),thumbnail:i.options.getString('thumbnail'),footer:i.options.getString('footer')}}); return i.reply(deny('Bienvenida configurada.')); }
 if(i.commandName==='vouch-config'){ if(!isAdmin(i))return i.reply(deny('Necesitas permisos de administrador.')); if(i.options.getSubcommand()==='reset'){await prisma.vouchConfig.upsert({where:{guildId:i.guildId},update:{enabled:false},create:{guildId:i.guildId,enabled:false,allowedRoleIds:[]}});return i.reply(deny('Vouches desactivados.'));} const ch=i.options.getChannel('canal'),raw=i.options.getString('roles'),roles=roleIds(i.guild,raw),cool=i.options.getInteger('cooldown')??60; if(raw&&!roles.length)return i.reply(deny('No se encontró ningún rol válido.')); await prisma.vouchConfig.upsert({where:{guildId:i.guildId},update:{enabled:true,channelId:ch.id,allowedRoleIds:roles,cooldown:cool,title:i.options.getString('titulo'),description:i.options.getString('descripcion'),color:i.options.getString('color'),image:i.options.getString('imagen'),thumbnail:i.options.getString('thumbnail'),footer:i.options.getString('footer')},create:{guildId:i.guildId,enabled:true,channelId:ch.id,allowedRoleIds:roles,cooldown:cool,title:i.options.getString('titulo'),description:i.options.getString('descripcion'),color:i.options.getString('color'),image:i.options.getString('imagen'),thumbnail:i.options.getString('thumbnail'),footer:i.options.getString('footer')}}); return i.reply(deny('Vouches configurados.')); }
 if(i.commandName==='vouch'){ const c=await prisma.vouchConfig.findUnique({where:{guildId:i.guildId}}); if(!c?.enabled)return i.reply(deny('Vouches desactivados.')); if(c.allowedRoleIds.length&&!c.allowedRoleIds.some(x=>i.member.roles.cache.has(x)))return i.reply(deny('No tienes permiso para usar /vouch.')); const last=cooldowns.get(i.guildId+':'+i.user.id)||0; if(Date.now()-last<c.cooldown*1000)return i.reply(deny('Espera antes de enviar otro vouch.')); const target=i.options.getUser('member'),type=i.options.getString('tipo'),rating=i.options.getInteger('rating'); if(target.id===i.user.id)return i.reply(deny('No puedes votarte a ti mismo.')); const modal=new ModalBuilder().setCustomId('vouch:'+target.id+':'+type+':'+rating).setTitle('Danos tu reseña'); modal.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('review').setLabel('Danos tu reseña').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(1000))); return i.showModal(modal); }
 if(i.commandName==='autoresponder'){ if(!isAdmin(i))return i.reply(deny('Necesitas permisos de administrador.')); const sub=i.options.getSubcommand(); if(sub==='add'){const trigger=i.options.getString('trigger').trim(),exists=await prisma.autoResponder.findFirst({where:{guildId:i.guildId,trigger:{equals:trigger,mode:'insensitive'}}}); if(exists)return i.reply(deny('Ya existe un autoresponder con ese trigger.')); await prisma.autoResponder.create({data:{guildId:i.guildId,trigger,response:i.options.getString('respuesta'),matchType:i.options.getString('modo')||'contains',embedTitle:i.options.getString('titulo'),embedDescription:i.options.getString('descripcion'),embedColor:i.options.getString('color')}}); return i.reply(deny('Autoresponder creado.')); } if(sub==='remove'){const trigger=i.options.getString('trigger').trim(),row=await prisma.autoResponder.findFirst({where:{guildId:i.guildId,trigger:{equals:trigger,mode:'insensitive'}}}); if(!row)return i.reply(deny('No existe ese autoresponder.')); await prisma.autoResponder.delete({where:{id:row.id}}); return i.reply(deny('Autoresponder eliminado.')); } const rows=await prisma.autoResponder.findMany({where:{guildId:i.guildId},orderBy:{createdAt:'asc'}}); return i.reply(deny(rows.length?rows.map(r=>'• **'+r.trigger+'** — '+r.matchType).join('\n'):'No hay autoresponders.')); }
 if(i.commandName==='presence'){ if(!isAdmin(i))return i.reply(deny('Necesitas permisos de administrador.')); if(i.options.getSubcommand()==='reset'){await prisma.presenceConfig.updateMany({data:{enabled:false}});await presence();return i.reply(deny('Rich Presence restablecida.'));} await prisma.presenceConfig.updateMany({data:{enabled:false}}); await prisma.presenceConfig.upsert({where:{guildId:i.guildId},update:{enabled:true,type:i.options.getString('tipo'),text:i.options.getString('texto')},create:{guildId:i.guildId,enabled:true,type:i.options.getString('tipo'),text:i.options.getString('texto')}}); await presence(); return i.reply(deny('Rich Presence actualizada.')); }
 if(i.commandName==='tickets'){ if(!isAdmin(i))return i.reply(deny('Necesitas permisos de administrador.')); const sub=i.options.getSubcommand(); if(sub==='log'){const ch=i.options.getChannel('canal');await prisma.guild.update({where:{id:i.guildId},data:{logChannelId:ch.id}});return i.reply(deny('Canal de logs configurado.'));} if(sub==='pregunta'){const c=await prisma.ticketCategory.findFirst({where:{id:i.options.getString('categoria'),panel:{guildId:i.guildId}}});if(!c)return i.reply(deny('Categoría no encontrada.'));const n=await prisma.ticketQuestion.count({where:{categoryId:c.id}});if(n>=5)return i.reply(deny('Máximo 5 preguntas por categoría.'));await prisma.ticketQuestion.create({data:{categoryId:c.id,label:i.options.getString('label'),placeholder:i.options.getString('placeholder'),required:i.options.getBoolean('obligatoria')??true}});return i.reply(deny('Pregunta añadida.'));} if(sub==='panel'){const p=await prisma.ticketPanel.create({data:{guildId:i.guildId,name:i.options.getString('nombre').trim(),channelId:i.options.getChannel('canal').id,title:i.options.getString('titulo'),description:i.options.getString('descripcion'),color:i.options.getString('color'),image:i.options.getString('imagen'),thumbnail:i.options.getString('thumbnail'),footer:i.options.getString('footer')}});return i.reply(deny('Panel creado. ID: '+p.id));} if(sub==='categoria'){const p=await prisma.ticketPanel.findFirst({where:{id:i.options.getString('panel'),guildId:i.guildId}});if(!p)return i.reply(deny('Panel no encontrado.'));const ids=roleIds(i.guild,i.options.getString('staff'));if(!ids.length)return i.reply(deny('Debes indicar al menos un rol de soporte válido.'));const c=await prisma.ticketCategory.create({data:{panelId:p.id,name:i.options.getString('nombre').trim(),description:i.options.getString('descripcion'),emoji:i.options.getString('emoji'),supportRoleIds:ids,discordCategoryId:i.options.getChannel('categoria-canal')?.id||null}});return i.reply(deny('Categoría creada. ID: '+c.id));} const p=await prisma.ticketPanel.findFirst({where:{id:i.options.getString('panel'),guildId:i.guildId},include:{categories:true}});if(!p)return i.reply(deny('Panel no encontrado.'));const ch=i.guild.channels.cache.get(p.channelId);if(!ch?.isTextBased())return i.reply(deny('Canal no encontrado.'));const menu=new StringSelectMenuBuilder().setCustomId('ticket:select:'+p.id).setPlaceholder('Selecciona una categoría').addOptions(p.categories.slice(0,25).map(c=>({label:c.name.slice(0,100),value:c.id,description:(c.description||'Abrir ticket').slice(0,100),emoji:c.emoji||undefined})));const emb=new EmbedBuilder().setTitle(p.title||p.name).setDescription(p.description||'Selecciona una categoría.').setColor(color(p.color));if(p.image)emb.setImage(p.image);if(p.thumbnail)emb.setThumbnail(p.thumbnail);if(p.footer)emb.setFooter({text:p.footer});await ch.send({embeds:[emb],components:[new ActionRowBuilder().addComponents(menu)]});return i.reply(deny('Panel publicado.')); }
 } catch(e){ logger.error('Interaction error',{error:e.message}); if(!i.replied&&!i.deferred)await i.reply(deny('Ocurrió un error.')); } });

client.login(env.DISCORD_TOKEN).catch(e=>{logger.error('Discord login failed',{error:e.message});process.exit(1);});